travis:
  secure:
    BINSTAR_TOKEN: uW9a8ySajW+40y0YjMb/RUJojrzEyFjBhnI/hfzv2w7kUi2zYoTa23vKdDW09EGn+gFXxYX5C4V5WaD13bcrHqJKWAFgkHGO7SVh9Jm575vxFQDNQrN9vYqZlaKk5innUGFr1yEj+JH/qHZqn638pJ/BGya0CCY2yRqj3SwkqfDbKvwXJH5MNN9JoCB6/pJvVHaQlug2y2hY8HtDNt5Lgr6eoLlcK7/lGr8NcW6fQaFvVUmOajNn9CdCnnQbxDnIXKuwiSSr86Z1/RyoIb2Q+qwlFL7ruUZvoV0x9GelXp15+9lax25P/xLVcYuyBaM3nwmq9rpnFYTsVGJ0CyJut91+cO9h0Dy6SrT49WlozzUC4EkzIt9ssaxfrRduwmDvDyiqO34tkhx49j3yzoOYsNvcn8wZHIoN2CbqvvR4eFLarO6biHqFKag86KsxypTto1RzzfDMnMErl32ZMTSHYQNHh9ftEDc5SPO3K8QN83vejJbW6gL8xvFW/f1lDNhtMqPQpHYOd42BJT+Si5iftPhbKIM9ArcvLkdOTf7vv7FkpADC/Or3fDjqKPsdZUJlcRAQSKsE3+xldm2H6x+eTdt7BOdqCR7mwo75NdbUJ2p7C7pWXrIhbHWzi4bM21ftXAZqoBkagirAtfVEr+Xf6ApLCeG2J8yzNPHY7Y6o/vI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
